### PR TITLE
healthz

### PR DESCRIPTION
**Pull request by nicksnyder**
part of https://github.com/sourcegraph/sourcegraph/issues/9124

### CODE REVIEW

**Review by sqs — APPROVED** [review]
This only is mounted once it has initialized, right?

**Comment by nicksnyder** [comment]
This endpoint will be available as soon as zoekt-webserver has bound its port. This is completely independent of when the index will be available. We may want something more sophisticated than this, but this is a minimum step. I don't see an obvious place to put a health check on the zoekt-indexer (and I am not familiar enough with the architecture yet).

**Comment by sqs** [comment]
Sounds good

**Comment by nicksnyder** [comment]
After reading the k8 docs, I actually don't think this is necessary. We can just add a TCP liveness check on the http port. A special endpoint is only really necessary if we want to check some other state for a readiness endpoint. I don't know enough about zoekt to know when it is "ready" and I think a simple liveness check might solve the issue.

See https://github.com/sourcegraph/infrastructure/pull/422 instead.

**Comment by nicksnyder** [comment]
Stephen made a good point on the other PR so I am going to merge this.
https://github.com/sourcegraph/infrastructure/pull/422#issuecomment-362483680

**Comment by nicksnyder** [comment]
How is zoekt deployed?

**Comment by sqs** [comment]
It's deployed to datacenter and a demo instance.

For the demo instance, see "Current Technical Details" at https://sourcegraph.sgdev.org/github.com/sourcegraph/docs-private/-/blob/201801/indexed-search.md#L69:7 and https://sourcegraph.sgdev.org/github.com/sourcegraph/infrastructure/-/blob/on-prem/demo/README.md#L3:69 (I filed the weird code formatting issue there).

**Comment by keegancsmith** [comment]
BTW this is good enough for ready. zoekt only starts listening on the port once the shards have been loaded.

**Pull request merged**
